// Növényadatok. Minden faj: [magyar név, latin név, a szerző megjegyzése, Ő/I, mérgező, fényigény, vízigény, méretosztály, képfájl, fotós, licenc]
// A "megjegyzés" a cikkben szereplő rövid jellemzés (Bardóczi Sándor listája).
// A fény/víz/méret besorolás ebből + általános kertészeti ismeretből származik — lásd módszertan.

const F = { TN:"Tűző nap", N:"Napos", NF:"Napos–félárnyék", FA:"Félárnyék", FAA:"Félárnyék–árnyék", A:"Árnyék" };
const V = { NA:"Nagyon alacsony", AL:"Alacsony", AK:"Alacsony–közepes", KO:"Közepes" };
const M = { XS:"XS · 50 cm alatt", S:"S · 0,5–1,5 m", MM:"M · 1,5–4 m", L:"L · 4–10 m", XL:"XL · 10 m felett" };

// ---------- 100 AJÁNLOTT ----------
const AJANLOTT = [
// --- Örökzöldek (10) ---
["Közönséges boróka","Juniperus communis","napos, száraz helyre","O",0,F.N,V.AL,M.MM,"Jeneverbes.jpg","Rasbak (holland Wikipédia)","CC BY-SA 3.0","Örökzöld"],
["Nehézszagú boróka","Juniperus sabina","száraz, meszes rézsűre; mérgező","O",1,F.N,V.NA,M.S,"Juniperus_sabina_cult1.jpg","MPF","CC BY 2.5","Örökzöld"],
["Kínai boróka","Juniperus chinensis","napos, meleg kertekbe","I",0,F.N,V.AL,M.MM,"Jun_chin_shoot.jpg","MPF (angol Wikipédia)","CC BY-SA 3.0","Örökzöld"],
["Közönséges tiszafa","Taxus baccata","napra vagy árnyékba; mérgező","O",1,F.FA,V.AK,M.L,"Taxus_baccata_MHNT.jpg","Didier Descouens","CC BY-SA 4.0","Örökzöld"],
["Erdei fenyő","Pinus sylvestris","levegős, inkább savanyú talajra","O",0,F.N,V.AL,M.XL,"Skuleskogen_pine.jpg","Mickaël Delcey (Silverkey)","CC BY-SA 3.0","Örökzöld"],
["Páncélfenyő","Pinus heldreichii","meszes, száraz termőhelyre","I",0,F.N,V.AL,M.XL,"Massiccio_del_Pollino,_Serra_di_Crispo_-_giardino_degli_dei_(pini_loricati).jpg","Fuoco Fatuo","CC0","Örökzöld"],
["Havasi törpefenyő","Pinus mugo","napos, drénezett helyre","I",0,F.N,V.AL,M.MM,"Pinus_mugo_cone_01.jpg","Agnieszka Kwiecień, Nova","CC BY 2.5","Örökzöld"],
["Kolorádói jegenyefenyő","Abies concolor","nagy kertbe, jó hőtűréssel","I",0,F.N,V.AK,M.XL,"Abies_concolor_Yosemite_NP.jpg","Puncsos","CC BY-SA 3.0","Örökzöld"],
["Atlaszcédrus","Cedrus atlantica","napos helyre; nagy termetű","I",0,F.N,V.AL,M.XL,"Cedrus atlantica in Jbel Lekraa.jpg","Mustapha Bassouh","CC BY-SA 4.0","Örökzöld"],
["Kerti pálmaliliom","Yucca filamentosa","tűző napra, száraz talajba","I",0,F.TN,V.NA,M.S,"Yucca_filamentosa.jpg","Moriori","Public domain","Örökzöld"],
// --- Lombhullató fák (20) ---
["Mezei juhar","Acer campestre","közepes, meleg- és mésztűrő","O",0,F.NF,V.AL,M.XL,"Acer_campestre_in_Appennino2.jpg","Galloramenu","CC BY-SA 3.0","Lombhullató fa"],
["Tatár juhar","Acer tataricum","kisebb, szárazságtűrő díszfa","O",0,F.N,V.AL,M.L,"Acer_tataricum_(fruits).jpg","Le.Loup.Gris","CC BY-SA 3.0","Lombhullató fa"],
["Háromkaréjú juhar","Acer monspessulanum","meleg, száraz helyre","I",0,F.N,V.AL,M.L,"Acer_monspessulanum_fg02.jpg","Fritz Geller-Grimm","CC BY-SA 2.5","Lombhullató fa"],
["Molyhos tölgy","Quercus pubescens","száraz, meszes kertbe","O",0,F.N,V.NA,M.XL,"Quercus_pubescens_Tuscany.jpg","Etrusko25","CC BY-SA 3.0","Lombhullató fa"],
["Csertölgy","Quercus cerris","nagy kertbe, mély talajra","O",0,F.N,V.AL,M.XL,"Quercus cerris 4.jpg","Franz Xaver","CC BY-SA 3.0","Lombhullató fa"],
["Magyar tölgy","Quercus frainetto","meleg fekvésbe, nagy gyökértérrel","O",0,F.N,V.AL,M.XL,"Ancient_oak_in_Paroria,_Strandzha,_Bulgaria.jpg","TodorBozhinov","CC BY-SA 4.0","Lombhullató fa"],
["Virágos kőris","Fraxinus ornus","meszes, köves helyre","O",0,F.N,V.AL,M.L,"Fraxinus_ornus_JPG2.jpg","Jean-Pol GRANDMONT","CC BY 3.0","Lombhullató fa"],
["Ezüsthárs","Tilia tomentosa","nagy, jó hő- és szárazságtűrő fa","O",0,F.NF,V.AK,M.XL,"Tilia tomentosa 1JPG.jpg","Jean-Pol GRANDMONT","CC BY 3.0","Lombhullató fa"],
["Déli ostorfa","Celtis australis","meleg, védett fekvésbe","I",0,F.N,V.AL,M.XL,"Celtis australis, Castelnau-de-Guers, Hérault.jpg","Christian Ferrer","CC BY-SA 3.0","Lombhullató fa"],
["Csörgőfa","Koelreuteria paniculata","kisebb, nap- és hőtűrő fa","I",0,F.N,V.AL,M.L,"(MHNT)_Koelreuteria_paniculata_-Leaves_and_inflorescences_-_Palais_Niel.jpg","Didier Descouens","CC BY-SA 4.0","Lombhullató fa"],
["Lepényfa","Gleditsia triacanthos","nagy, laza árnyékot adó fa","I",0,F.N,V.AL,M.XL,"Gleditsia_triacanthos_(Honeylocust)_(38246396371).jpg","Plant Image Library","CC BY-SA 2.0","Lombhullató fa"],
["Japánakác","Styphnolobium japonicum","nagy, kiváló hő- és várostűrő fa","I",0,F.N,V.AL,M.XL,"Sophora_japonica_JPG2Aa.jpg","Jean-Pol GRANDMONT","CC BY 3.0","Lombhullató fa"],
["Közönséges júdásfa","Cercis siliquastrum","napos, védett helyre","I",0,F.N,V.AL,M.L,"PikiWiki_Israel_3421_Geography_of_Israel.jpg","אורנה לוטן","CC BY 2.5","Lombhullató fa"],
["Törökmogyoró","Corylus colurna","mész- és szárazságtűrő","I",0,F.NF,V.AL,M.XL,"Corylus_colurna_subadriatic_dinaric_mountains_Orjen.JPG","Orjen, Pavle Cikovac","CC BY-SA 3.0","Lombhullató fa"],
["Komlógyertyán","Ostrya carpinifolia","köves, meszes talajra is","I",0,F.NF,V.AL,M.XL,"Ostrya_carpinifolia_3.jpg","Franz Xaver","CC BY-SA 3.0","Lombhullató fa"],
["Házi berkenye","Sorbus domestica","meleg, száraz termőhelyre","O",0,F.N,V.AL,M.XL,"Sorbus_domestica_FruitsLeaves_BotGardBln0906a.JPG","BotBln","CC BY-SA 3.0","Lombhullató fa"],
["Vadkörte","Pyrus pyraster","edzett, ökológiailag értékes","O",0,F.N,V.AL,M.L,"Rosaceae_-_Pyrus_pyraster_-_Perastro-1.JPG","Hectonichus","CC BY-SA 3.0","Lombhullató fa"],
["Sajmeggy","Prunus mahaleb","kisebb fa száraz, meszes helyre","O",0,F.N,V.NA,M.L,"Prunus mahaleb inflorescence16.jpg","Pancrat","CC BY-SA 3.0","Lombhullató fa"],
["Vadalma","Malus sylvestris","kisebb, biodiverzitást növelő fa","O",0,F.N,V.AL,M.L,"Malus_sylvestris_005.JPG","H. Zell","CC BY-SA 3.0","Lombhullató fa"],
["Fehér eperfa","Morus alba","edzett; termése szennyezhet","I",0,F.N,V.AL,M.XL,"Rosales_-_Morus_alba_-_3.jpg","Emőke Dénes","CC BY-SA 4.0","Lombhullató fa"],
// --- Cserjék (20) ---
["Cserszömörce","Cotinus coggygria","tűző napra, meszes talajra","O",0,F.TN,V.AL,M.L,"Cotinus_coggygria5.jpg","Alexander Dunkel","CC BY-SA 2.5","Cserje"],
["Húsos som","Cornus mas","napra vagy félárnyékba; ehető","O",0,F.NF,V.AL,M.L,"CornusMas_Fruits_01.jpg","B.navez","CC BY-SA 3.0","Cserje"],
["Egybibés galagonya","Crataegus monogyna","tövises sövénybe","O",0,F.NF,V.AL,M.L,"Hawthorn_fruit.JPG","Elstro","CC BY 3.0","Cserje"],
["Kökény","Prunus spinosa","edzett, tövises, sarjadzó","O",0,F.N,V.AL,M.MM,"Prunus spinosa 130403.jpg","BerndH","CC BY-SA 3.0","Cserje"],
["Varjútövis","Rhamnus cathartica","száraz, meszes helyre","O",1,F.NF,V.AL,M.MM,"Illustration_of_Rhamnus_catharticus_63-cropped.png","F. E. Köhler","Public domain","Cserje"],
["Közönséges fagyal","Ligustrum vulgare","nyírható sövénynek","O",1,F.NF,V.AL,M.MM,"Wilde_liguster_(Ligustrum_vulgare).jpg","Rasbak","CC BY-SA 3.0","Cserje"],
["Ostorménfa","Viburnum lantana","napra vagy félárnyékba","O",0,F.NF,V.AL,M.MM,"Viburnum_lantana_a1.jpg","Opioła Jerzy","CC BY 2.5","Cserje"],
["Bibircses kecskerágó","Euonymus verrucosus","félárnyékba; mérgező","O",1,F.FA,V.AL,M.MM,"Euonymus_verrucosus_20080907b.jpg","Bff","CC BY-SA 3.0","Cserje"],
["Gyepűrózsa","Rosa canina","tüskés, természetközeli sövénybe","O",0,F.N,V.AL,M.MM,"Divlja_ruza_cvijet_270508.jpg","Roberta F.","CC BY-SA 3.0","Cserje"],
["Jajrózsa","Rosa spinosissima","száraz rézsűre; sarjadzik","O",0,F.N,V.NA,M.S,"Rosa_pimpinellifolia.jpg","Velela","CC BY-SA 2.5","Cserje"],
["Sóskaborbolya","Berberis vulgaris","tövises, szárazságtűrő","O",0,F.NF,V.AL,M.MM,"Illustration_Berberis_vulgaris0.jpg","ismeretlen szerző","Public domain","Cserje"],
["Szirti fanyarka","Amelanchier ovalis","köves, meszes helyre","O",0,F.N,V.AL,M.MM,"Amelanchier_ovalis01.jpg","Tigerente","CC BY-SA 3.0","Cserje"],
["Pukkanó dudafürt","Colutea arborescens","száraz, napos helyre","O",1,F.N,V.NA,M.MM,"20140515Colutea_arborescens02.jpg","AnRo0002","CC0","Cserje"],
["Homoktövis","Hippophae rhamnoides","homokra is; sarjadzó, kétlaki","O",0,F.N,V.NA,M.MM,"Hippophae_rhamnoides-01_(xndr).JPG","ismeretlen szerző (Commons)","CC BY-SA 3.0","Cserje"],
["Krisztustövis","Paliurus spina-christi","meleg helyre, sövénynek","O",0,F.TN,V.NA,M.MM,"Paliurus_fg01.jpg","Fritz Geller-Grimm","CC BY-SA 2.5","Cserje"],
["Tűztövis","Pyracantha coccinea","tövises, félörökzöld sövénycserje","I",1,F.NF,V.AL,M.MM,"Feuerdorn_(Pyracantha_coccinea).JPG","noebse","CC BY-SA 2.5","Cserje"],
["Sudárzsálya","Salvia yangii","napos, száraz, sovány talajra","I",0,F.TN,V.NA,M.S,"Russian_sage_by_RO_IV.jpg","Rationalobserver","CC BY-SA 4.0","Cserje"],
["Kékszakáll","Caryopteris × clandonensis","napos, meleg helyre","I",0,F.N,V.AL,M.S,"Caryopteris clandonensis C.jpg","Wouter Hagens","Public domain","Cserje"],
["Barátcserje","Vitex agnus-castus","meleg, védett fekvésbe","I",0,F.N,V.AL,M.MM,"Vitex_agnus-castus_1.JPG","Cillas","CC BY-SA 4.0","Cserje"],
["Spanyol rekettye","Spartium junceum","forró helyre; mérgező","I",1,F.TN,V.NA,M.MM,"Spartium_junceum_(habitus).jpg","Hans Hillewaert","CC BY-SA 3.0","Cserje"],
// --- Napos évelők (25) ---
["Közönséges cickafark","Achillea millefolium","száraz gyepbe","O",0,F.N,V.NA,M.S,"Achillea_millefolium_(bright).jpg","SAplants","CC BY-SA 4.0","Napos évelő"],
["Jószagú cickafark","Achillea filipendulina","magas, sárga virágú","I",0,F.N,V.AL,M.S,"Achillea filipendulina flowers.jpg","Yerpo","CC BY-SA 3.0","Napos évelő"],
["Ligeti zsálya","Salvia nemorosa","hosszan virágzó","O",0,F.N,V.AK,M.S,"Salvia_nemorosa-IMG_3624.jpg","C T Johansson","CC BY-SA 3.0","Napos évelő"],
["Orvosi zsálya","Salvia officinalis","meleg, száraz helyre","I",0,F.N,V.AL,M.S,"Salvia_officinalis0.jpg","Kurt Stüber","CC BY-SA 3.0","Napos évelő"],
["Keskenylevelű levendula","Lavandula angustifolia","napos, meszes talajra","I",0,F.TN,V.NA,M.S,"Lavandula_angustifolia_-_Köhler–s_Medizinal-Pflanzen-087.jpg","F. E. Köhler","Public domain","Napos évelő"],
["Kerti macskamenta","Nepeta × faassenii","hosszan virágzó, kis vízigényű","I",0,F.N,V.NA,M.S,"Nepeta_faassenii6.jpg","KENPEI","CC BY-SA 3.0","Napos évelő"],
["Gyapjas tisztesfű","Stachys byzantina","száraz napra","I",0,F.N,V.NA,M.XS,"0_Stachys_byzantina_-_Yvoire_(2).JPG","Jean-Pol GRANDMONT","CC BY-SA 3.0","Napos évelő"],
["Kék szamárkenyér","Echinops ritro","száraz, beporzóbarát évelő","O",0,F.N,V.NA,M.S,"ECHINOPS_RITRO_-_APIS_-_IB-544_(Panical_blau).JPG","Isidre blanc","CC BY-SA 4.0","Napos évelő"],
["Kék iringó","Eryngium planum","száraz, ásványi talajra","O",0,F.N,V.NA,M.S,"Eryngium_planum_bgiu.jpg","ismeretlen szerző (Commons)","CC BY-SA 3.0","Napos évelő"],
["Macedón varfű","Knautia macedonica","légies, hosszan virágzó","I",0,F.N,V.AL,M.S,"Knautia Knautia macedonica Flower Insect 1626px.jpg","Derek Ramsey","CC BY-SA 3.0","Napos évelő"],
["Galambszínű ördögszem","Scabiosa columbaria","meszes, száraz helyre","O",0,F.N,V.AL,M.S,"Scabiosa_columbaria_Butterfly_Blue_2.jpg","Stan Shebs","CC BY-SA 3.0","Napos évelő"],
["Vastövű imola","Centaurea scabiosa","természetközeli kiültetésbe","O",0,F.N,V.AL,M.S,"Centaurea_scabiosa.jpg","C. A. M. Lindman","Public domain","Napos évelő"],
["Lila ökörfarkkóró","Verbascum phoeniceum","napos, sovány talajra","O",0,F.N,V.NA,M.S,"Verbascum_phoeniceum2.jpg","Jeffdelonge","CC BY-SA 3.0","Napos évelő"],
["Sárga korbácsliliom","Asphodeline lutea","meleg, drénezett helyre","I",0,F.N,V.NA,M.S,"Asphodeline lutea 4.jpg","Franz Xaver","CC BY-SA 3.0","Napos évelő"],
["Dalmát nőszirom","Iris pallida","napos, száraz rézsűre","I",0,F.N,V.NA,M.S,"Iris_pallida_specie.jpg","Pamwik","CC BY-SA 4.0","Napos évelő"],
["Keskenylevelű bazsarózsa","Paeonia tenuifolia","csak kertészetből","O",0,F.N,V.AL,M.XS,"Воронець_09.jpg","Михайло Гончаров","CC BY-SA 4.0","Napos évelő"],
["Bablevelű varjúháj","Hylotelephium telephium","pozsgás, későn virágzó","O",0,F.N,V.NA,M.XS,"Sedum_telephium_240808e.jpg","Bernd Haynold","CC BY-SA 3.0","Napos évelő"],
["Fehér varjúháj","Sedum album","köves, szélsőségesen száraz helyre","O",0,F.TN,V.NA,M.XS,"White_stonecrop,_Autonomous_Province_of_Bolzano_–_South_Tyrol,_Italy_imported_from_iNaturalist_photo_382140510.jpg","Thierry Arbault","CC BY 4.0","Napos évelő"],
["Házi kövirózsa","Sempervivum tectorum","sekély, köves közegbe","I",0,F.TN,V.NA,M.XS,"Sempervivum tectorum FR 2012.jpg","JLPC","CC BY-SA 3.0","Napos évelő"],
["Buglyos fátyolvirág","Gypsophila paniculata","napos, meszes talajra","O",0,F.N,V.NA,M.S,"Gypsophila_paniculata_sl17.jpg","Stefan.lefnaer","CC BY-SA 4.0","Napos évelő"],
["Sárga macskahere","Phlomis russeliana","erős, terjedő évelő","I",0,F.NF,V.AL,M.S,"Turkish_sage_flowers.jpg","Dicklyon","CC BY-SA 4.0","Napos évelő"],
["Csillagőszirózsa","Aster amellus","későn virágzik","O",0,F.N,V.AL,M.S,"Asteraceae_-_Aster_amellus.JPG","Hectonichus","CC BY-SA 3.0","Napos évelő"],
["Gyémántfű","Calamagrostis brachytricha","napra vagy félárnyékba","I",0,F.NF,V.AK,M.S,"Bloeiaren van Diamantgras. 04-09-2022. (d.j.b) 01.jpg","Dominicus Johannes Bergsma","CC BY-SA 4.0","Napos évelő"],
["Ametiszt csenkesz","Festuca amethystina","száraz, sovány talajra","O",0,F.N,V.NA,M.XS,"Festuca_amethystina_-_Berlin_Botanical_Garden_-_IMG_8537.JPG","Daderot","Public domain","Napos évelő"],
["Őszi nyúlfarkfű","Sesleria autumnalis","tartós, alacsony díszfű","I",0,F.NF,V.AL,M.XS,"Sesleria_autumnalis_kz1.jpg","Krzysztof Ziarnek, Kenraiz","CC BY-SA 4.0","Napos évelő"],
// --- Árnyéki talajtakarók (8) ---
["Közönséges borostyán","Hedera helix","száraz árnyékba","O",1,F.FAA,V.AL,M.XS,"Hedera_helix_Dover.jpg","kallerna","CC BY-SA 4.0","Árnyéki talajtakaró"],
["Kis télizöld","Vinca minor","örökzöld, gyors talajtakaró","O",1,F.FAA,V.AL,M.XS,"Vinca_minor_Nashville.jpg","Ryan Kaldari","Public domain","Árnyéki talajtakaró"],
["Illatos gólyaorr","Geranium macrorrhizum","kiváló száraz árnyéki faj","I",0,F.FAA,V.AL,M.XS,"Geranium_macrorrhizum_flowers.jpg","Hardyplants","Public domain","Árnyéki talajtakaró"],
["Havasi tündérvirág","Epimedium alpinum","fák alá","I",0,F.FAA,V.AL,M.XS,"Epimedium cf alpinum Alppivarjohiippa Alpsockblomma C IMG 9102.JPG","Anneli Salo","CC BY-SA 3.0","Árnyéki talajtakaró"],
["Erdei ciklámen","Cyclamen purpurascens","csak kertészetből","O",1,F.A,V.AL,M.XS,"Cyclamen_purpurascens_Orchi_01.jpg","Orchi","CC BY-SA 3.0","Árnyéki talajtakaró"],
["Ujjas sás","Carex digitata","szárazabb erdőkertbe","O",0,F.FAA,V.AL,M.XS,"Carex_digitata_kz02.jpg","Krzysztof Ziarnek, Kenraiz","CC BY-SA 4.0","Árnyéki talajtakaró"],
["Erdélyi nyúlfarkfű","Sesleria heufleriana","félárnyékba is","I",0,F.FA,V.AL,M.XS,"Sesleria_heufleriana_-_Berlin_Botanical_Garden_-_IMG_8614.JPG","Daderot","Public domain","Árnyéki talajtakaró"],
["Kapotnyak","Asarum europaeum","humuszos, mulcsolt árnyékba","O",1,F.A,V.AK,M.XS,"Asarum_europaeum_170406.jpg","Bernd Haynold","CC BY 2.5","Árnyéki talajtakaró"],
// --- Futó- és kúszónövények (7) ---
["Erdei iszalag","Clematis vitalba","nagy helyre, metszéssel","O",1,F.NF,V.AK,M.XL,"Clematis-vitalba-Waldrebe(Samenstand).jpg","Michael Gasperl (Migas)","CC BY-SA 3.0","Kúszónövény"],
["Jerikói lonc","Lonicera caprifolium","napra vagy félárnyékba","O",0,F.NF,V.AK,M.L,"Lonicera_caprifolium002.jpg","Meneerke bloem","CC BY-SA 3.0","Kúszónövény"],
["Bortermő szőlő","Vitis vinifera","pergolára, mélyebb talajba","I",0,F.N,V.AK,M.L,"Edle Weinrebe, 'Vitis vinifera' subsp. 'vinifera.jpg","eflon (Alex, Ithaca NY)","CC BY 2.0","Kúszónövény"],
["Tapadó vadszőlő","Parthenocissus tricuspidata","falak befuttatására","I",0,F.NF,V.KO,M.XL,"Poertschach_Hauptstrasse_Parthenocissus_tricuspidata_Blattwerk_04062015_4423.jpg","Johann Jaritz","CC BY-SA 4.0","Kúszónövény"],
["Mandzsu kivi","Actinidia arguta","pergolára; terméshez öntözést kér","I",0,F.NF,V.KO,M.L,"Weiki01.jpg","Björn Appel","CC BY-SA 3.0","Kúszónövény"],
["Trombitafolyondár","Campsis radicans","sarjainak korlátozásával","I",0,F.N,V.AL,M.L,"Campsis_radicans_-_Trumpet_Creeper.jpg","Fritzflohrreynolds","CC BY-SA 3.0","Kúszónövény"],
["Közönséges komló","Humulus lupulus","évelő tövű, gyors kúszó","O",0,F.NF,V.KO,M.L,"Hopfen1.jpg","ismeretlen szerző (Commons)","CC BY-SA 2.5","Kúszónövény"],
// --- Gyeppótlók (10) ---
["Keskenylevelű kakukkfű","Thymus serpyllum","ritkán taposott napos helyre","O",0,F.N,V.NA,M.XS,"Thymus_serpyllum.JPG","MurielBendel","CC BY-SA 4.0","Gyeppótló"],
["Korai kakukkfű","Thymus praecox","kövek közé, mérsékelt taposásra","I",0,F.N,V.NA,M.XS,"Thymus praecox bethisy-saint-martin 60 18062008 4.jpg","Olivier Pichard","CC BY-SA 3.0","Gyeppótló"],
["Fehér here","Trifolium repens","nyírható és taposható; aszályban ritkulhat","O",0,F.N,V.AK,M.XS,"Trifolium_repens_-_white_clover_on_way_from_Govindghat_to_Gangria_at_Valley_of_Flowers_National_Park_-_during_LGFC_-_VOF_2019_(1).jpg","Vinayaraj","CC BY-SA 4.0","Gyeppótló"],
["Eperhere","Trifolium fragiferum","szárazság-, só- és taposástűrő","O",0,F.N,V.AL,M.XS,"TrifoliumFragiferum2.jpg","Christian Fischer","CC BY-SA 3.0","Gyeppótló"],
["Ezüstös cickafark","Achillea crithmifolia","alacsony, nyírható gyeppótló","I",0,F.N,V.NA,M.XS,"Achillea crithmifolia 2016-04-22 8489.jpg","Salicyna","CC BY-SA 4.0","Gyeppótló"],
["Kopasz porcika","Herniaria glabra","mérsékelten taposott helyre","O",0,F.N,V.NA,M.XS,"Herniaria_glabra_2005.06.12_14.50.22.jpg","Michael Becker","CC BY-SA 3.0","Gyeppótló"],
["Közönséges gyíkfű","Prunella vulgaris","virágos, nyírható gyeppótló","O",0,F.NF,V.AK,M.XS,"Prunella_vulgaris_-_harilik_käbihein.jpg","Ivar Leidus","CC BY-SA 3.0","Gyeppótló"],
["Tavaszi pimpó","Potentilla neumanniana","gyengén taposott felületre","O",0,F.N,V.NA,M.XS,"Château_de_Logne_-_Potentille_printanière.jpg","JackyM59","CC BY-SA 4.0","Gyeppótló"],
["Juhcsenkesz","Festuca ovina","száraz, ritkán nyírt gyepbe","O",0,F.N,V.NA,M.XS,"Illustration_Festuca_ovina0.jpg","ismeretlen szerző","Public domain","Gyeppótló"],
["Karcsú fényperje","Koeleria macrantha","természetközeli száraz gyepbe","O",0,F.N,V.NA,M.XS,"Koeleria_macrantha.JPG","Don Pedro28","CC BY-SA 3.0","Gyeppótló"]
];

// ---------- 20 INVAZÍV ----------
// [magyar, latin, indoklás (szerző), fás/lágy, uniós jegyzékes, mérgező, kép, fotós, licenc, sorszám]
const INVAZIV = [
["Mirigyes bálványfa","Ailanthus altissima","Rendkívül agresszíven sarjadzó, uniós jegyzékes özönfa.","F",1,1,"Götterbaum_(Ailanthus_altissima).jpg","Darkone","CC BY-SA 2.5",1],
["Fehér akác","Robinia pseudoacacia","Gyökérsarjakkal terjed, nitrogéndúsítással átalakítja az élőhelyeket.","F",0,1,"Robina9146.JPG","Pollinator (angol Wikipédia)","CC BY-SA 3.0",2],
["Zöld juhar","Acer negundo","Főként ártereken és vízpartokon terjed tömegesen.","F",0,0,"Acer_negundo_44809168.jpg","CK Kelly","CC BY 4.0",3],
["Amerikai kőris","Fraxinus pennsylvanica","Ártéri erdőkben kiszorítja az őshonos fafajokat.","F",0,0,"Fraxinus_pensylvanica_a1.jpg","Jerzy Opioła","CC BY-SA 3.0",4],
["Kései meggy","Prunus serotina","Erdőkben sűrű második lombkoronaszintet képez.","F",0,1,"Prunus serotina 155393379.jpg","Seth Wollney","CC BY 4.0",5],
["Nyugati ostorfa","Celtis occidentalis","Madarak terjesztik, száraz erdőkben és városi területeken terjed.","F",0,0,"Celtis_occidentalis_20090606.jpg","Chhe","Public domain",6],
["Keskenylevelű ezüstfa","Elaeagnus angustifolia","Száraz gyepeket, homoki és szikes élőhelyeket foglal el.","F",0,0,"Korina_2012-05-15_Elaeagnus_angustifolia_1.jpg","Katrin Schneider / korina.info","CC BY-SA 4.0",7],
["Gyalogakác","Amorpha fruticosa","Ártereken és vízpartokon összefüggő cserjéseket alkot.","F",0,0,"Amorpha_fruticosa_05.JPG","Dalgial","CC BY-SA 3.0",8],
["Ecetfa","Rhus typhina","Erősen sarjadzik, a kertből könnyen kijut.","F",0,0,"Сумах_оленерогий_(Сумах_пушистый,_Уксусное_дерево)_-_Rhus_typhina_-_Staghorn_sumac_-_Влакнест_шмак_-_Essigbaum_(23408707041).jpg","Katya (Moszkva)","CC BY-SA 2.0",9],
["Vörös tölgy","Quercus rubra","Erdőkben spontán újul, avarja és árnyékolása átalakítja az aljnövényzetet.","F",0,0,"Quercus_rubra_@_Tortworth_Court.jpg","ismeretlen szerző (Commons)","Public domain",10],
["Közönséges selyemkóró","Asclepias syriaca","Tarackokkal terjedő, uniós jegyzékes özönnövény.","L",1,1,"Asclepias_syriacus.tif","Amos Oliver Doyle","CC BY-SA 4.0",11],
["Kanadai aranyvessző","Solidago canadensis","Gyepeket és parlagokat borít el.","L",0,0,"Solidago_canadensis_20050815_248.jpg","Georg Slickers","CC BY-SA 4.0",12],
["Magas aranyvessző","Solidago gigantea","Nedvesebb gyepekben és ártereken alkot állományokat.","L",0,0,"Solidago gigantea A.jpg","Wouter Hagens","Public domain",13],
["Japánkeserűfű","Reynoutria japonica","Rizómatöredékből is regenerálódik, kiirtása rendkívül nehéz.","L",0,0,"Reynoutria_japonica_in_Brastad_1.jpg","W.carter","CC0",14],
["Óriáskeserűfű","Reynoutria sachalinensis","Hatalmas, fajszegény állományokat képez.","L",0,0,"GiantKnotweed053.jpg","Velocicaptor","Public domain",15],
["Bíbor nebáncsvirág","Impatiens glandulifera","Vízfolyások mentén gyorsan terjedő, uniós jegyzékes faj.","L",1,0,"Impatiens_glandulifera_0004.JPG","H. Zell","CC BY-SA 3.0",16],
["Amerikai alkörmös","Phytolacca americana","Erdőkben és bolygatott területeken terjed; mérgező.","L",0,1,"Pokeweed_bush_in_Northumberland_County,_Pennsylvania.JPG","Jakec","CC BY-SA 4.0",17],
["Süntök","Echinocystis lobata","Egyéves kúszónövényként elborítja a vízparti növényzetet.","L",0,0,"Echinocystis_lobata.jpg","Aung","Public domain",18],
["Kaukázusi medvetalp","Heracleum mantegazzianum","Uniós jegyzékes; nedve súlyos fényérzékeny bőrgyulladást okozhat.","L",1,1,"Giant_hogweed_in_Dunnyduff_Woods,_Keith.jpg","Lucas Kendall","CC BY-SA 4.0",19],
["Afrikai tollborzfű","Cenchrus setaceus","Uniós jegyzékes inváziós díszfű; telepítése és forgalmazása tilos.","L",1,0,"Starr_040217-0077_Pennisetum_setaceum.jpg","Forest & Kim Starr","CC BY 3.0",20]
];

// ---------- NEM FENNTARTHATÓ (6) ----------
const FENNTART = [
["Nyugati tuja","Thuja occidentalis",1,"10–15 m; kertekben jellemzően 2–4 m-es nyírt sövény",
 "Eredeti élőhelye a nedves erdő és a láperdő — nagy és folyamatos a vízigénye. Aszályos nyarakon tömegesen barnul el és pusztul, mégis évtizedekig ez volt a legnépszerűbb sövénynövény. Tujont tartalmaz, ami mérgező.",
 "Közönséges tiszafa vagy boróka; nyírott lombhullató sövénynek fagyal, galagonya",
 "Thuja_occidentalis.jpg","ismeretlen szerző","Public domain"],
["Hamisciprus","Chamaecyparis lawsoniana",0,"Hazánkban jellemzően 5–15 m, sövényként alacsonyabban tartva",
 "Csapadékos, párás óceáni klíma fája — a hazai forró, száraz nyarat rosszul viseli. Gyökérrothadásra és aszálystresszre egyaránt érzékeny, a legyengült példányok gyorsan barnulnak.",
 "Boróka, tiszafa vagy páncélfenyő a top100 listáról",
 "Chamaecyparis_lawsoniana_Dorena1.jpg","US Forest Service (Dorena GRC)","Public domain"],
["Japánjuhar","Acer palmatum",0,"3–8 m, lassú növekedésű kisfa",
 "Párás, félárnyékos élőhelyek fája. A hazai tűző napon és száraz levegőn a levele perzselődik, széle barnára szárad; tartós aszályban visszahal. Sok kertbe kifejezetten kedvezőtlen, napos helyre ültetik.",
 "Tatár juhar, háromkaréjú juhar vagy cserszömörce hasonló őszi lombszínért",
 "Acer_palmatum0.jpg","Kurt Stüber","CC BY-SA 3.0"],
["Lucfenyő","Picea abies",0,"30–50 m, sekélyen gyökerező nagy fa",
 "Hegyvidéki, hűvös és párás klíma fája — az alföldi meleg, száraz nyár alapvetően nem felel meg neki. Sekély gyökérzete miatt az aszályt rosszul viseli, a legyengült fák pedig szúbogár-fertőzésnek esnek áldozatul.",
 "Erdei fenyő vagy páncélfenyő a top100 listáról",
 "Kuusk_Keila-Paldiski_rdt_ääres.jpg","Ivar Leidus","CC BY-SA 3.0 ee"],
["Közönséges nyír","Betula pendula",0,"15–25 m, viszonylag rövid életű fa",
 "Hűvösebb, csapadékosabb éghajlat fája, sekély gyökérzettel és nagy párologtatással. Tartós aszályban korán sárgul és lombot hullat, gyakran néhány év alatt le is pusztul.",
 "Virágos kőris, tatár juhar vagy sajmeggy",
 "Betula_pendula_Finland.jpg","Percita (Flickr)","CC BY-SA 2.0"],
["Angolperje-gyep („angolpázsit”)","Lolium perenne",0,"Nyírt gyepfelület",
 "A klasszikus, sűrű, mindig zöld pázsit a kert messze legnagyobb vízfogyasztója — a cikk kifejezetten „a legnagyobb vízpazarló” néven említi. Nyáron heti több tíz liter/m² öntözést kíván, különben kisül; vízkorlátozás idején tartósan fenntarthatatlan. A két kép ugyanannak a lakónegyednek a gyepeit mutatja, hat hét különbséggel: júniusban és a rákövetkező forró, száraz júliusban.",
 "Gyeppótlók: kakukkfű, eperhere, ezüstös cickafark, juhcsenkesz — vagy kisebb, öntözött díszgyep + mulcsozott ágyások",
 "2022-06-09 12 22 34 A freshly mowed front lawn along Aquetong Lane in the Mountainview section of Ewing Township, Mercer County, New Jersey.jpg","Famartin","CC BY-SA 4.0",
 // összehasonlító csúszka: balra húzva a kiszáradt, jobbra húzva az öntözött állapot
 {left:{img:"2022-07-26 10 33 24 Brown, dry lawn after an extended period of hot and dry weather along Seven Oaks Lane in the Mountainview section of Ewing Township, Mercer County, New Jersey.jpg", by:"Famartin", lic:"CC BY-SA 4.0", cap:"Július – aszály után"},
  right:{img:"2022-06-09 12 22 34 A freshly mowed front lawn along Aquetong Lane in the Mountainview section of Ewing Township, Mercer County, New Jersey.jpg", by:"Famartin", lic:"CC BY-SA 4.0", cap:"Június – frissen nyírva"}}]
];

// ---------- MEDITERRÁN – TÉVÚT (6) ----------
const MEDITERRAN = [
["Olajfa","Olea europaea",0,"Hazájában 8–15 m; nálunk cserépben 1,5–3 m",
 "Tartósan −8 … −10 °C alatt lefagy, a fiatal példányok már ennél enyhébb fagyot is megsínylik. A cikk által említett havas, komoly mínuszos telet szabadföldön nem éli túl — csak edényben, fagymentes teleltetéssel tartható, ami éves cipekedést és téli tárolóhelyet jelent.",
 "Olajfa-hangulatú, ezüstös lombért: keskenylevelű ezüstfa helyett homoktövis, sudárzsálya, gyapjas tisztesfű",
 "Olivesfromjordan.jpg","Nickfraser","CC BY-SA 3.0"],
["Leander","Nerium oleander",1,"2–4 m, cserépben kisebb",
 "Nagyjából −5 °C-ig bírja, tehát nálunk szabadföldön nem telel át. Ráadásul minden része erősen mérgező. Cserépben tartható, de akkor rendszeres öntözést és fagymentes teleltetést igényel — vagyis épp a víztakarékos, alacsony fenntartású cél ellen hat.",
 "Hosszan, dúsan virágzó szárazságtűrő cserjékért: barátcserje, kékszakáll, spanyol rekettye",
 "Nerium_oleander_flowers_leaves.jpg","Alvesgaspar","CC BY 2.5"],
["Fügekaktusz („medvetalp kaktusz”)","Opuntia ficus-indica",0,"2–5 m, telepszerűen terjed",
 "A szárazságot kiválóan bírja, de a hazai telek nedvességét nem: fagyott, átázott talajban elrothad. A fajtársai közül csak néhány, valóban fagytűrő Opuntia jöhet szóba, és azoknak is tökéletes vízelvezetés kell. Tövisei ráadásul apró, nehezen eltávolítható horgas serték.",
 "Pozsgás hatásért télállóan: fehér varjúháj, házi kövirózsa, bablevelű varjúháj, kerti pálmaliliom",
 "Dikenli_İncir_(Opuntia_ficus-indica)_Gaziantep_Turkey.IMG_1104.jpg","YG01","CC BY 4.0"],
["Babér","Laurus nobilis",0,"Hazájában 10–18 m; nálunk cserépben 1–2 m",
 "Körülbelül −8 °C-ig tűri a fagyot, de a hazai téli szárazszél a levelét akkor is kiszárítja, amikor a hőmérséklet még nem lenne végzetes. Szabadföldön csak a legvédettebb, városi mikroklímájú helyeken kísérletezhető, egyébként cserepes, teleltetett növény.",
 "Örökzöld, nyírható lombfalért: közönséges tiszafa, tűztövis, közönséges fagyal",
 "Starr-071024-0195-Laurus_nobilis-leaves-Enchanting_Floral_Gardens_of_Kula-Maui_(24867859296).jpg","Forest & Kim Starr","CC BY 3.0 us"],
["Babérmeggy","Prunus laurocerasus",1,"2–6 m, sűrű örökzöld sövény",
 "Ez télállóbb a többinél, de két gond van vele: nagy a vízigénye, tehát aszályban pont úgy pusztul, mint a tuja; a magja és a levele pedig ciánglikozidot tartalmaz, vagyis mérgező. Több nyugat-európai országban már inváziósként tartják számon, madarak terjesztik az erdőkbe.",
 "Örökzöld sövénynek: közönséges tiszafa vagy tűztövis; lombhullatónak fagyal, galagonya",
 "Karayemiş-8.jpg","Karduelis","Public domain"],
["Narancs","Citrus × sinensis",0,"Hazájában 6–10 m; nálunk cserépben 1–2 m",
 "Mindössze −3 … −5 °C-ig bírja, tehát nálunk kizárólag edényes, fagymentesen teleltetett növény. Télen világos, hűvös helyiséget kíván, nyáron rendszeres öntözést és tápoldatozást — a víztakarékos kert szempontjából a lehető legrosszabb választás.",
 "Illatos virágért szárazságtűrően: júdásfa, barátcserje, jerikói lonc",
 "OrangeBloss_wb.jpg","Ellen Levy Finch","CC BY-SA 3.0"]
];

module.exports = { AJANLOTT, INVAZIV, FENNTART, MEDITERRAN, F, V, M };
